#!/usr/bin/env python3
"""
gen_mig_stubs.py -- hand-written stand-ins for MIG-generated headers.

The original build ran CMU MIG over kernel/mach/*.defs to produce
mach/<name>_user.h (client stubs) and mach/<name>_server.h (server
dispatch).  No MIG implementation is available in this environment and
porting one is out of scope for M2, so we emit C prototypes whose
signatures are derived directly from the .defs files:

  * simpleroutine/routine -> kern_return_t
  * `arg : type = ... ctype: T` -> parameter of type T
  * `arg : type` (no ctype)     -> parameter of the declared MIG type
  * `polymorphic` argument      -> extra mach_msg_type_name_t parameter
                                  immediately after the port (this is what
                                  CMU MIG generates; verified against the
                                  call sites in vm/memory_object.c)
  * `data : pointer_t`         -> (pointer_t data,
                                  mach_msg_type_number_t dataCnt), because
                                  std_types.defs declares
                                  `type pointer_t = ^array[] of ...`
  * SEQNOS conditional seqno   -> omitted (we build with SEQNOS off,
                                  the default configuration)

Only the headers actually #included by MI are generated:
  mach/memory_object_user.h     (from mach/memory_object.defs)
  mach/memory_object_default.h  (from mach/memory_object_default.defs;
                                 memory_object_data_terminate is #if 0'd
                                 out in the .defs itself)

These stubs are compile-only: the real IPC marshalling code must come
from a working MIG (or hand-written servers) in M3.  Recorded as tech
debt in M2-REPORT.md.

Usage: gen_mig_stubs.py <output-dir>   (writes <output-dir>/mach/*.h)
"""
import os
import sys

PREAMBLE = """\
/*
 * GENERATED by mach3/tools/gen_mig_stubs.py -- do not edit.
 * Hand-written stand-in for the MIG-generated header.
 * Source interface: kernel/mach/%(defs)s
 * Signatures derived per the rules in gen_mig_stubs.py; SEQNOS off.
 * COMPILE-ONLY stub -- real marshalling needs MIG (tech debt, see
 * M2-REPORT.md).
 */
#ifndef %(guard)s
#define %(guard)s

#include <mach/kern_return.h>
#include <mach/boolean.h>
#include <mach/message.h>
#include <mach/mach_types.h>
#include <mach/machine/vm_types.h> /* vm_offset_t, vm_size_t (MD) */
#include <mach/std_types.h>
#include <mach/memory_object.h>

"""

EPILOGUE = """
#endif /* %(guard)s */
"""


def proto(ret, name, params):
    """C prototype string."""
    if not params:
        return "%s %s(void);" % (ret, name)
    return "%s %s(\n\t%s);" % (ret, name, ",\n\t".join(params))


# (name, [(type, param), ...]) -- from mach/memory_object.defs
MEMORY_OBJECT_USER = [
    ("memory_object_init", [
        ("mach_port_t", "memory_object"),
        ("mach_port_t", "memory_control"),
        ("mach_port_t", "memory_object_name"),
        ("vm_size_t", "memory_object_page_size")]),
    ("memory_object_terminate", [
        ("mach_port_t", "memory_object"),
        ("mach_port_t", "memory_control"),
        ("mach_port_t", "memory_object_name")]),
    ("memory_object_copy", [
        ("mach_port_t", "old_memory_object"),
        ("mach_port_t", "old_memory_control"),
        ("vm_offset_t", "offset"),
        ("vm_size_t", "length"),
        ("mach_port_t", "new_memory_object")]),
    ("memory_object_data_request", [
        ("mach_port_t", "memory_object"),
        ("mach_port_t", "memory_control"),
        ("vm_offset_t", "offset"),
        ("vm_size_t", "length"),
        ("vm_prot_t", "desired_access")]),
    ("memory_object_data_unlock", [
        ("mach_port_t", "memory_object"),
        ("mach_port_t", "memory_control"),
        ("vm_offset_t", "offset"),
        ("vm_size_t", "length"),
        ("vm_prot_t", "desired_access")]),
    ("memory_object_data_write", [
        ("mach_port_t", "memory_object"),
        ("mach_port_t", "memory_control"),
        ("vm_offset_t", "offset"),
        ("pointer_t", "data"),
        ("mach_msg_type_number_t", "dataCnt")]),
    ("memory_object_lock_completed", [
        ("mach_port_t", "memory_object"),
        ("mach_msg_type_name_t", "memory_objectPoly"),
        ("mach_port_t", "memory_control"),
        ("vm_offset_t", "offset"),
        ("vm_size_t", "length")]),
    ("memory_object_supply_completed", [
        ("mach_port_t", "memory_object"),
        ("mach_msg_type_name_t", "memory_objectPoly"),
        ("mach_port_t", "memory_control"),
        ("vm_offset_t", "offset"),
        ("vm_size_t", "length"),
        ("kern_return_t", "result"),
        ("vm_offset_t", "error_offset")]),
    ("memory_object_data_return", [
        ("mach_port_t", "memory_object"),
        ("mach_port_t", "memory_control"),
        ("vm_offset_t", "offset"),
        ("pointer_t", "data"),
        ("mach_msg_type_number_t", "dataCnt"),
        ("boolean_t", "dirty"),
        ("boolean_t", "kernel_copy")]),
    ("memory_object_change_completed", [
        ("mach_port_t", "memory_object"),
        ("mach_msg_type_name_t", "memory_objectPoly"),
        ("boolean_t", "may_cache"),
        ("memory_object_copy_strategy_t", "copy_strategy")]),
]

# From mach/memory_object_default.defs (data_terminate is #if 0 in .defs)
MEMORY_OBJECT_DEFAULT = [
    ("memory_object_create", [
        ("mach_port_t", "old_memory_object"),
        ("mach_port_t", "new_memory_object"),
        ("vm_size_t", "new_object_size"),
        ("mach_port_t", "new_control_port"),
        ("mach_port_t", "new_name"),
        ("vm_size_t", "new_page_size")]),
    ("memory_object_data_initialize", [
        ("mach_port_t", "memory_object"),
        ("mach_port_t", "memory_control_port"),
        ("vm_offset_t", "offset"),
        ("pointer_t", "data"),
        ("mach_msg_type_number_t", "dataCnt")]),
]


# From device/device_reply.defs (userprefix ds_; reply_port_t is polymorphic)
DEVICE_REPLY = [
    ("ds_device_open_reply", [
        ("mach_port_t", "reply_port"),
        ("mach_msg_type_name_t", "reply_portPoly"),
        ("kern_return_t", "return_code"),
        ("mach_port_t", "device_port")]),
    ("ds_device_write_reply", [
        ("mach_port_t", "reply_port"),
        ("mach_msg_type_name_t", "reply_portPoly"),
        ("kern_return_t", "return_code"),
        ("int", "bytes_written")]),
    ("ds_device_write_reply_inband", [
        ("mach_port_t", "reply_port"),
        ("mach_msg_type_name_t", "reply_portPoly"),
        ("kern_return_t", "return_code"),
        ("int", "bytes_written")]),
    ("ds_device_read_reply", [
        ("mach_port_t", "reply_port"),
        ("mach_msg_type_name_t", "reply_portPoly"),
        ("kern_return_t", "return_code"),
        ("io_buf_ptr_t", "data"),
        ("mach_msg_type_number_t", "dataCnt")]),
    ("ds_device_read_reply_inband", [
        ("mach_port_t", "reply_port"),
        ("mach_msg_type_name_t", "reply_portPoly"),
        ("kern_return_t", "return_code"),
        ("io_buf_ptr_inband_t", "data"),
        ("mach_msg_type_number_t", "dataCnt")]),
]

DEVICE_PREAMBLE = """\
/*
 * GENERATED by mach3/tools/gen_mig_stubs.py -- do not edit.
 * Hand-written stand-in for the MIG-generated header.
 * Source interface: device/device_reply.defs (userprefix ds_)
 * COMPILE-ONLY stub -- real marshalling needs MIG (tech debt, see
 * M2-REPORT.md).
 */
#ifndef %(guard)s
#define %(guard)s

#include <mach/kern_return.h>
#include <mach/message.h>
#include <mach/mach_types.h>
#include <mach/machine/vm_types.h>
#include <device/device_types.h>

"""

# Minimal stand-in for the MIG-generated device_pager_server.c, which
# dev_pager.c #includes as C source (renaming memory_object_server to
# device_pager_server).  Signatures follow the MIG server convention;
# bodies are compile-only placeholders (no link in M2).
PAGER_SERVER_C = """\
/*
 * GENERATED by mach3/tools/gen_mig_stubs.py -- do not edit.
 * Compile-only stand-in for MIG-generated device_pager_server.c
 * (subsystem memory_object, from mach/memory_object.defs).
 * Real dispatch needs MIG (tech debt, see M2-REPORT.md).
 */
#include <mach/boolean.h>
#include <mach/message.h>
#include <mach/mig_errors.h>

boolean_t
device_pager_server(request, reply)
\tmach_msg_header_t *request;
\tmach_msg_header_t *reply;
{
\t/* compile-only: no real dispatch (MIG not available in M2) */
\trequest = request;
\treply = reply;
\treturn FALSE;
}

mig_routine_t
device_pager_server_routine(request)
\tmach_msg_header_t *request;
{
\t/* compile-only: no real dispatch (MIG not available in M2) */
\trequest = request;
\treturn (mig_routine_t)0;
}
"""


def write_stub(path, defs, guard, routines):
    with open(path, "w") as f:
        f.write(PREAMBLE % {"defs": defs, "guard": guard})
        for name, params in routines:
            plist = ["%s %s" % (t, p) for t, p in params]
            f.write("extern " + proto("kern_return_t", name, plist) + "\n")
        f.write(EPILOGUE % {"guard": guard})


def write_device_stub(path, guard, routines):
    with open(path, "w") as f:
        f.write(DEVICE_PREAMBLE % {"guard": guard})
        for name, params in routines:
            plist = ["%s %s" % (t, p) for t, p in params]
            f.write("extern " + proto("kern_return_t", name, plist) + "\n")
        f.write(EPILOGUE % {"guard": guard})


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "build/gen"
    machdir = os.path.join(outdir, "mach")
    os.makedirs(machdir, exist_ok=True)
    write_stub(os.path.join(machdir, "memory_object_user.h"),
               "memory_object.defs", "_GEN_MEMORY_OBJECT_USER_H_",
               MEMORY_OBJECT_USER)
    write_stub(os.path.join(machdir, "memory_object_default.h"),
               "memory_object_default.defs",
               "_GEN_MEMORY_OBJECT_DEFAULT_H_", MEMORY_OBJECT_DEFAULT)

    # device MIG stubs
    devdir = os.path.join(outdir, "device")
    os.makedirs(devdir, exist_ok=True)
    write_device_stub(os.path.join(devdir, "device_reply.h"),
                      "_GEN_DEVICE_REPLY_H_", DEVICE_REPLY)
    with open(os.path.join(devdir, "device_pager_server.c"), "w") as f:
        f.write(PAGER_SERVER_C)
    print("gen_mig_stubs.py: wrote 2 MIG stubs to %s" % machdir)
    print("gen_mig_stubs.py: wrote device stubs to %s" % devdir)


if __name__ == "__main__":
    main()
