#!/usr/bin/env python3
"""
gen_config.py -- generate Mach 3 "config" headers for the ARM port.

Replicates what the BSD `config` tool did with kernel/conf/MASTER:
for every `options FOO` line it emitted OPTIONS/foo_lower.h containing
`#define FOO <0|1>`.  We generate the same set of headers directly,
with values chosen for our target (single-core ARMv7, QEMU -M virt,
later Luckfox RV1103).

Also generates:
  cpus.h        -- from `pseudo-device cpus N`  ->  #define NCPUS N
  platforms.h   -- from `platform XXX` lines    ->  #define XXX 1
  bootstrap_symbols.h, cmucs_disk.h, dli.h      -- legacy OPTIONS entries
  mach_mp_debug.h, mach_lock_mon.h, time_stamp.h  -- for kern/lock_mon.c
                                                  (legacy file, not in
                                                  conf/files; kept out
                                                  of the default build)

Usage: gen_config.py <output-dir>
"""
import os
import sys

# option -> (value, rationale).  Mirrors kernel/conf/MASTER option set.
OPTIONS = {
    # --- MI options from kernel/conf/MASTER ---
    "MACH_ASSERT":     (1, "compile in assertions; wanted for bring-up"),
    "MACH_DEBUG":      (0, "IPC debugging interface; off for minimal kernel"),
    "MACH_FIXPRI":     (1, "fixed-priority threads; default on since MK80"),
    "MACH_HOST":       (1, "host resource allocation (vm/host.c needs it)"),
    "MACH_IPC_COMPAT": (0, "old 2.5 IPC interface; not needed"),
    "MACH_IPC_DEBUG":  (0, "IPC debugging calls; off"),
    "MACH_IPC_TEST":   (0, "IPC testing code/printfs; off"),
    "MACH_KDB":        (1, "kernel debugger (ddb); useful for bring-up"),
    "MACH_LDEBUG":     (0, "simple-lock sanity checks; off"),
    "MACH_PAGEMAP":    (1, "paged-out page map hints; in STD since 1992"),
    "MACH_PCSAMPLE":   (0, "pc sample histogram; needs MD profiling (M3)"),
    "MACH_TTD":        (0, "TTD remote kernel debugging; off"),
    "NORMA_IPC":       (0, "no NORMA network IPC"),
    "NORMA_DEVICE":    (0, "no NORMA unified device names"),
    "NORMA_VM":        (0, "no NORMA virtual memory"),
    "NORMA_TASK":      (0, "no NORMA task support"),
    "NORMA_ETHER":     (0, "no NORMA over ethernet"),
    "MACH_COUNTERS":   (1, "kernel counters (c_counters)"),
    "MACH_VM_DEBUG":   (0, "VM debugging calls; off"),
    "FAST_TAS":        (0, "restartable atomic seqs need MD trap support (M3)"),
    "HW_FOOTPRINT":    (0, "cache footprint support; off"),
    "POWER_SAVE":      (0, "needs MD power conservation hooks (M3)"),
    "SIMPLE_CLOCK":    (1, "no HW clock rollover handling in MI"),
    "STAT_TIME":       (1, "statistical timing"),
    "XPR_DEBUG":       (0, "kernel tracing (xpr); off"),
    "NET_ATM":         (0, "ATM kernel traps; off"),
    # --- generated OPTIONS/*.h not tied to a MASTER `options` line ---
    "MACH_MACHINE_ROUTINES": (0, "no MD machine_routines yet (M3)"),
    "BOOTSTRAP_SYMBOLS":     (0, "no bootstrap symbol table loading"),
    "CMUCS_DISK":            (0, "CMUCS disk label support; off"),
    "DLI":                   (0, "DLI network interface; off"),
}

# platform lines (kernel/conf/<arch>/MASTER `platform` entries), ARM port.
PLATFORMS = {
    "ARM":       "CPU family ARM",
    "ARMV7":     "ARMv7-A architecture",
    "QEMU_VIRT": "QEMU -M virt board (bring-up target)",
    "RV1103":    "Luckfox Pico Mini SoC (later target)",
}

NCPUS = 1  # pseudo-device cpus 1 (single-core Cortex-A7)

# Legacy headers for kern/lock_mon.c (not in conf/files; stale upstream).
LEGACY = {
    "mach_mp_debug.h": ("MACH_MP_DEBUG", 0, "MP debug locking; off (UP)"),
    "mach_lock_mon.h": ("MACH_LOCK_MON", 0, "lock monitoring; off"),
    "time_stamp.h":    ("TIME_STAMP", 0, "timestamped locks; off"),
}

# BSD-compat sys/ headers (the original build had a sys/ include dir;
# these are minimal freestanding versions for --target=arm-none-eabi).
SYS_VARARGS_H = """\
/*
 * GENERATED by mach3/tools/gen_config.py -- do not edit.
 * Old BSD <varargs.h> interface (va_dcl / 1-arg va_start) over compiler
 * builtins.  Used by kern/{debug,printf,sscanf,bootstrap}.c and
 * ddb/db_output.c.
 */
#ifndef _SYS_VARARGS_H_
#define _SYS_VARARGS_H_

typedef __builtin_va_list va_list;

/* K&R-style variable args declaration: f(va_alist) va_dcl { ... } */
#define va_dcl int va_alist;

#undef va_start
#undef va_arg
#undef va_end
#undef va_copy
#define va_start(ap)        ((void)(ap), (void)&va_alist)
#define va_arg(ap, type)    __builtin_va_arg((ap), type)
#define va_end(ap)          ((void)0)
#define va_copy(dst, src)   __builtin_va_copy((dst), (src))
/*
 * NOTE (M2 compile-only): the historical BSD varargs.h did raw stack
 * hackery that assumed stack-passed arguments (VAX/MIPS) and cannot work
 * on ARM (AAPCS passes the first words in registers); clang's
 * __builtin_va_start additionally refuses non-variadic functions.
 * This shim exists only so the 1993 sources COMPILE.  The correct M3
 * fix is converting these files to ANSI <stdarg.h> (see M2-REPORT.md).
 */

#endif /* _SYS_VARARGS_H_ */
"""

SYS_STDARGS_H = """\
/*
 * GENERATED by mach3/tools/gen_config.py -- do not edit.
 * Old name for <stdarg.h> (only referenced from dead `#if later` code
 * in kern/sscanf.c, but provided for completeness).
 */
#ifndef _SYS_STDARGS_H_
#define _SYS_STDARGS_H_

#include <stdarg.h>

#endif /* _SYS_STDARGS_H_ */
"""

SYS_REBOOT_H = """\\
/*
 * GENERATED by mach3/tools/gen_config.py -- do not edit.
 * Minimal <sys/reboot.h>: boot flags used by kern/bootstrap.c.
 * Values follow 4.3BSD; exact bits do not matter for compile-only M2.
 */
#ifndef _SYS_REBOOT_H_
#define _SYS_REBOOT_H_

#define RB_ASKNAME  0x001  /* ask for file name to reboot from */
#define RB_SINGLE   0x002  /* reboot to single user only */
#define RB_NOSYNC   0x004  /* don't sync before reboot */
#define RB_HALT     0x008  /* halt instead of reboot */
#define RB_INITNAME 0x010  /* alternate init path */
#define RB_DFLTROOT 0x020  /* use compiled-in root device */
#define RB_KDB      0x040  /* enter kernel debugger */
#define RB_RDONLY   0x080  /* mount root read-only */
#define RB_DUMP     0x100  /* dump kernel memory */
#define RB_DEBUGGER 0x200  /* Mach: enter debugger on boot */

#endif /* _SYS_REBOOT_H_ */
"""

# Machine-dependent globals that MI references but nothing declares
# (the 1993 build relied on implicit declarations).  Force-included via
# -include; the real definitions come from the MD layer (M3).
MD_GLOBALS_H = """\
/*
 * GENERATED by mach3/tools/gen_config.py -- do not edit.
 * Declarations of MD-provided globals referenced by MI.
 * Force-included in every TU via -include (build-mi.sh).
 */
#ifndef _GEN_MD_GLOBALS_H_
#define _GEN_MD_GLOBALS_H_

extern int boothowto;  /* boot flags; defined by MD startup (cf. mips_init.c) */

#endif /* _GEN_MD_GLOBALS_H_ */
"""

HEADER_TMPL = """\
/*
 * GENERATED by mach3/tools/gen_config.py -- do not edit.
 * Replicates the BSD `config` tool output for kernel/conf/MASTER
 * (option {opt}, target: ARMv7/QEMU-virt).
 * Rationale: {why}
 */
#ifndef _GEN_{guard}_H_
#define _GEN_{guard}_H_

#define {opt} {val}

#endif /* _GEN_{guard}_H_ */
"""


def write_header(outdir, filename, opt, val, why):
    guard = filename.replace(".", "_").upper()
    with open(os.path.join(outdir, filename), "w") as f:
        f.write(HEADER_TMPL.format(guard=guard, opt=opt, val=val, why=why))


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "build/gen"
    os.makedirs(outdir, exist_ok=True)

    for opt, (val, why) in sorted(OPTIONS.items()):
        write_header(outdir, opt.lower() + ".h", opt, val, why)

    # cpus.h (pseudo-device)
    with open(os.path.join(outdir, "cpus.h"), "w") as f:
        f.write(HEADER_TMPL.format(guard="CPUS_H", opt="NCPUS",
                                   val=NCPUS,
                                   why="pseudo-device cpus %d (UP ARMv7)"
                                   % NCPUS))

    # platforms.h (platform lines)
    with open(os.path.join(outdir, "platforms.h"), "w") as f:
        f.write("/*\n * GENERATED by mach3/tools/gen_config.py -- do not edit.\n"
                " * Platform defines for the ARM port.\n */\n"
                "#ifndef _GEN_PLATFORMS_H_\n#define _GEN_PLATFORMS_H_\n\n")
        for plat, why in sorted(PLATFORMS.items()):
            f.write("#define %-12s 1 /* %s */\n" % (plat, why))
        f.write("\n#endif /* _GEN_PLATFORMS_H_ */\n")

    # legacy headers (lock_mon.c only)
    for filename, (opt, val, why) in LEGACY.items():
        write_header(outdir, filename, opt, val, why)

    # BSD-compat sys/ headers
    sysdir = os.path.join(outdir, "sys")
    os.makedirs(sysdir, exist_ok=True)
    for name, content in [("varargs.h", SYS_VARARGS_H),
                          ("stdargs.h", SYS_STDARGS_H),
                          ("reboot.h", SYS_REBOOT_H)]:
        with open(os.path.join(sysdir, name), "w") as f:
            f.write(content)

    # MD globals referenced by MI (force-included via -include)
    with open(os.path.join(outdir, "md_globals.h"), "w") as f:
        f.write(MD_GLOBALS_H)

    n = len(OPTIONS) + 2 + len(LEGACY) + 4
    print("gen_config.py: wrote %d headers to %s" % (n, outdir))


if __name__ == "__main__":
    main()
