/*
 * mach3/kernel/arm/devices.c -- device configuration tables (M3).
 *
 * Normally generated by the BSD `config` tool from the config file.
 * M3 has no devices yet; provide empty tables so MI links.
 */
#include <device/conf.h>
#include <device/device_types.h>

/* Empty device name list (no configured devices). */
struct dev_ops	dev_name_list[1];
int		dev_name_count = 0;

/* Empty indirect device list. */
struct dev_indirect	dev_indirect_list[1];
int			dev_indirect_count = 0;

/* Root device name (for bootstrap). */
char	*root_name = 0;
